apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: sample-app
          image: docker.pkg.github.com/matthiasfalk/sample_app/sample_app:1606826161
      imagePullSecrets:
        - name: dockerconfigjson-github-com
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app
spec:
  type: LoadBalancer
  ports:
    - port: 8000
  selector:
    app: sample-app
