name: sample_app

### 1. 2 3
on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  # TODO: Change variable to your image's name.
  CONTAINER_REGISTRY: docker.pkg.github.com
  IMAGE_NAME: sample_app

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      tag: ${{env.IMAGE_TAG}}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask flake8 pytest pytest-cov

    - name: Lint tests
      run: |
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Pytests
      run: |
        pytest tests/test_app.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      ### Login to registry
    - name: Login to Registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    ### Get version
    - name: Get version
      run: |
        echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV
        echo $IMAGE_TAG

    ### Build docker image
    - name: Build docker image
      run: |
        docker build . -f Dockerfile -t ${{env.CONTAINER_REGISTRY}}/${{ github.repository }}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}

    ### Push docker image
    - name: Push to Registry
      run: |
        docker push ${{env.CONTAINER_REGISTRY}}/${{ github.repository }}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    ### Set kube context
    - name: Set Kube context
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig # Azure credentials
        kubeconfig: "${{ secrets.KUBECONFIG }}"
        context: 'sample-cluster'
      id: setcontext

      # Deploy app to AKS
    - name: Deploy to aks
      uses: azure/k8s-deploy@v1.2
      with:
        manifests: |
          deployment.yaml
        images: |
          ${{env.CONTAINER_REGISTRY}}/${{ github.repository }}/${{env.IMAGE_NAME}}:${{needs.build.outputs.tag}}
        imagepullsecrets: |
          dockerconfigjson-github-com


